### ISSUE TITLE
No actions for my Atom C++ Project

### ISSUE THREAD

**Issue by tan-wei** [isundaylee/atom-ide-ccls#3]
After I get used to `cquery`, I decide to try `ccls`. But after I finish all the steps, I think the plugin in my Atom editor do not work. No autocompletion, no extra highlights, no `go-to declaritions` ...

I have checked all this:
  - `Atom`: `ide-ccls` installed (0.3.0), `atom-ide-ui` installed (0.13.0), `ccls.exe` full path location correct (if I changed it into a wrong one, `ide-ccls` will complain that ccls can not open)
 - `ccls`: (version: e496d4e5db47b602b14fe53bd556f11d0b025f52, the latest in Github), works well when I run it in `CMD`, and can manually index the source codes of the project with parameter `--index=path` 

So do I miss some thing? Thanks very much.

Extra information:
  - `Atom` version: 1.36.0 x64-windows
  - `compile_commands.json` generated by CMake, which works well with `cquery`

**Comment by isundaylee** [comment]
Hmm interesting. Sorry I wasn't able to test it on Windows since I don't have a Windows machine. Can you try the following: 

1. Open the C++ project folder in Atom.
2. Choose "Window: Reload" in the Command Palette. 
3. Choose "Console" in the new debugger pane that opened, and see if there are any log messages printed. 

It'd be great if you can give me a screenshot from step 3. 

Thanks!

**Comment by tan-wei** [comment]
I have tried, but I'm confused about step 3. Is in bottom window we can see log messages?
![image](https://user-images.githubusercontent.com/28227509/56704315-3584b180-673f-11e9-9421-4252e8d600b9.png)
I can't see any.

Then I think, maybe my `compile_commands.json` in the wrong directory which `ccls` doesn't know the actual location. In the C++ project, directory `build` is located in the root, so `compile_commands.json` locates in `build/`. Any thing I can do to tell `ccls` now?

**Comment by isundaylee** [comment]
Sorry about the late reply. Just to confirm, did you use the command in the following screenshot to reload the window? 

![Screen Shot 2019-04-28 at 1 24 31 AM](https://user-images.githubusercontent.com/1572861/56859123-6ee23a80-6954-11e9-92ab-57d3dc274c60.png)

For me, after the window is reloaded, the dev console is opened automatically, like this:

![Screen Shot 2019-04-28 at 1 25 23 AM](https://user-images.githubusercontent.com/1572861/56859127-7f92b080-6954-11e9-87bf-54040411f4bd.png)

**Comment by isundaylee** [comment]
As for `compile_commands.json`, what I usually do is to just sym-link it to the project root folder 😃 :

```
# In the project root folder, do this:
ln -s build/compile_commands.json .
```

**Comment by tan-wei** [comment]
Ok, I'v tried to open dev console in other way. It seems that in Windows, dev console can't be opened automatically by just reloading the window.
We can see some errors printed in the console:
![image](https://user-images.githubusercontent.com/28227509/56860586-c58a5b80-69ca-11e9-8b6f-e455c37072d8.png)
![image](https://user-images.githubusercontent.com/28227509/56860592-d33fe100-69ca-11e9-9e20-1b0f54d8d93c.png)
First, I guess the errors are related to log file for some reasons. However, disable verbose log will act the same.
I also tried to create a sym-link to `compile_commands.json`, just the same as before.

Do I need to give further information? Thanks for your reply, slow reply is OK for me, so do not feel that sorry :-P.
Hope you have a good weekend.

**Comment by isundaylee** [comment]
Thanks for the information! It looks like the issue is that I set the default log path for `ccls` to `/tmp/ccls.log`, which does not exist on Windows. Can you try going into "Application: Show Preferences" -> "Packages" -> "ide-ccls" -> "Settings", and change the value of the log path to `stderr`? 

![Screen Shot 2019-04-28 at 10 46 27 AM](https://user-images.githubusercontent.com/1572861/56866033-f787c780-69a2-11e9-9329-f95146ff426c.png)

**Comment by tan-wei** [comment]
Wow, it works. `ccls` now works well and I can enjoy the plugin. I think provide a windows specific default value to `Path for ccls to write its log` can fix this issue.

**Comment by isundaylee** [comment]
That's great! I'm thinking about just putting `stderr` down as the default value for all platforms. This would mean that the log does not get stored into a file by default. But I think this is fine, since people who need logs can just go into settings and change it to a path they like?

**Comment by tan-wei** [comment]
I think so. Most of the users do not care about the log.

**Comment by isundaylee** [comment]
@tan-wei I just pushed a commit that fixes this, and will release a new version soon. Do you mind if I add your name to the change log as the contributor for reporting this issue?

**Comment by tan-wei** [comment]
Sorry for the late replying. Feel good if you add my name in the change log. :-P
Thanks!
